---
title: "final hw"
date: "2023-09-29"
output:
  html_document: default
---

```{r, warning=TRUE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(tinytex))
```

```{r}
# CellLinesIC50 <- read.csv("G:/내 드라이브/UofM Biostatistics/BIOSTAT 607-1 R MODULE/FinalHW/CellLinesIC50.csv")
CellLinesIC50 <- read.csv("CellLinesIC50.csv")
# View(CellLinesIC50)
```

Question#1
```{r}
#is.na(CellLinesIC50)
#colSums(is.na(CellLinesIC50))
##How many missing values does the data frame CellLinesIC50 have?----
sum(colSums(is.na(CellLinesIC50))) # Return 2294, there are total 2294 missing values.

##Which variable in CellLinesIC50 has the most missing values?----
which.max(colSums(is.na(CellLinesIC50))) #Return "AGE" variable has the most missing Values
```

Question 2
```{r}
cnt = nrow(subset(CellLinesIC50, !is.na(SEX) & !is.na(AGE)))
cat(sprintf("[CHECK] cnt : %s", cnt), "\n")

cntFemaleOver70 = nrow(subset(CellLinesIC50, !is.na(SEX) & !is.na(AGE) & SEX == "Female" & AGE > 70))
resultAns02 = (cntFemaleOver70 / cnt) * 100
cat(sprintf("[CHECK] resultAns02 : %s", resultAns02), "\n")
```


Question 3
```{r}
#Question 3----
##mean and median of the TMB variable (ignoring any missing values of TMB)----
mean(CellLinesIC50$TMB,na.rm = TRUE) #Return 19.42108
median(CellLinesIC50$TMB,na.rm = TRUE) #Return 10.41667

##How many missing values does the TMB variable have?----
sum(is.na(CellLinesIC50$TMB)) # Return 2

##How many observations have a TMB value greater than 10?----
library(dplyr)
TMB <- select(CellLinesIC50,TMB)
nrow(filter(TMB,TMB>10)) # Return 529

```


Qeustion 4
```{r}
#Question 4----
CellLinesIC50 <- CellLinesIC50 %>%
  mutate(
    TMB_cat = case_when(
      TMB <= 10 ~ "low",
      TMB > 10 & TMB <= 25 ~ "medium", #check question updated version=>done!!
      TMB > 25 ~ "high"
      
    )
  )
#View(CellLinesIC50)
head(CellLinesIC50)

```


Question 5
```{r}
#Question 5----
CellLinesIC50 %>%
  group_by(TMB_cat) %>%
  summarise(Median_Age = median(AGE, na.rm = TRUE))

```

Question 6
```{r}
resultAns06 = CellLinesIC50 %>%
  filter(!is.na(TMB_cat)) %>%
  # dplyr::filter(TMB_cat %in% c("medium")) %>%
  dplyr::group_by(TMB_cat) %>%
  summarise(across(starts_with("ic50"), mean, na.rm = TRUE))
print(resultAns06)
```

#Question 7
```{r}
HighMutTMB = CellLinesIC50 %>%
  filter(TMB_cat == "high" & MUTATION_RATE > 200)

# print(HighMutTMB)

resultAns07 = HighMutTMB %>%
  group_by(CANCER_TYPE) %>%
  summarize(count = n()) %>%
  arrange(desc(count)) %>%
  head(5)

print(resultAns07)
```


# question 8
```{r}
resultAns08 = CellLinesIC50 %>%
  summarise(across(contains("ic50"), mean, na.rm = TRUE)) %>%
  pivot_longer(cols = everything()) %>%
  arrange(desc(value)) %>% 
   slice_head(n = 1)

print(resultAns08)
```

# question 9
```{r}
selData = CellLinesIC50 %>%
  filter(!is.na(TMB_cat)) %>%
  rename(val = resultAns08$name) %>% 
  mutate(
    meanVal = log(val)
  )
# print(selData)

resultAns08 = ggplot(selData, aes(x = meanVal)) + 
  geom_histogram(bins = 30, fill = 'blue', alpha = 0.5) +
  facet_wrap(~TMB_cat) +
  labs(
    title = paste("Histogram of log(IC50)"),
    x = "log(IC50)",
    y = "Frequency"
  )

print(resultAns08)
```

# question 10
```{r}

colList = CellLinesIC50 %>% 
  select(matches("ic50", ignore.case = TRUE)) %>% 
  colnames()

resultAns10 = CellLinesIC50 %>%
  tidyr::gather(key = "drug", value = "ic50", all_of(colList)) %>%
  group_by(row_number()) %>%
  slice(which.max(ic50)) %>%
  ungroup() %>% 
  count(drug) %>% 
  arrange(desc(n))

print(resultAns10)
```

# question 11
```{r}
CellLinesIC50Long = CellLinesIC50 %>%
  gather(key = "drug", value = "ic50", starts_with("ic50_")) %>%
  mutate(drug = str_remove(drug, "ic50_")) %>%
  arrange(PATIENT_ID)

head(CellLinesIC50Long, 3)
```

# question 12
```{r}
resultAns12 = ggplot(CellLinesIC50Long, aes(x = drug, y = log(ic50))) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Boxplot of log(ic50) for each Drug", y = "log(ic50)", x = "Drug")

print(resultAns12)

resultAns12 = ggplot(CellLinesIC50Long, aes(x = drug, y = log(ic50))) +
  geom_violin() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Violin Plot of log(ic50) for each Drug", y = "log(ic50)", x = "Drug")

print(resultAns12)
```