---
title: "Lab 11: Dashboards in R"
author: "Sangwon Yum"
date: "`r Sys.Date()`"
geometry: margin=1in
fontsize: 11pt
output:
  flexdashboard::flex_dashboard:
    orientation: columns
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE, eval = TRUE, fig.width = 6, warning = FALSE,
  message = FALSE,
  fig.asp = 0.618, out.width = "80%", dpi = 120,
  fig.align = "center", cache = FALSE
)

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(flexdashboard))
suppressPackageStartupMessages(library(crosstalk))

# pokemon.csv 파일 읽기
pokemon = readr::read_csv("pokemon.csv")
```


SidebarName {.sidebar}
----------------------

```{r, echo=FALSE}
shared_pokemon = SharedData$new(pokemon)
filter_select("poke_type", "Pokemon Type", shared_pokemon, ~`Type 1`)
```

Column
-------------------------------------

### Total by Type 1

```{r, echo=FALSE}
p = ggplot(shared_pokemon, aes(x = `Type 1`, y = Total, fill = `Type 1`)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "Pokemon Types: A Comparison of Total Stats", x = "Type 1", y = "Total") +
  theme(axis.text.x = element_text(angle = 45))

ggplotly(p)
```

Column
-------------------------------------

### Defense vs Attack

```{r, echo=FALSE}
# ggplot2를 이용한 산점도 생성
p = ggplot(shared_pokemon, aes(x = Defense, y = Attack, color = `Type 1`)) +
  geom_point() +
  theme_minimal() +
  labs(title = "Pokemon Battle Capabilities: Comparing Defense and Attack", x = "Defense", y = "Attack")

ggplotly(p)
```
