---
title: "Lab 9: Using APIs"
author: "Sangwon Yum"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: yes
    dev: cairo_pdf
    fig_caption: yes
    number_sections: yes
    toc: no
    df_print: kable
mainfont: "Malgun Gothic"
---

```{r setup, include = FALSE}
# Set knitr options
knitr::opts_chunk$set(
  echo = TRUE, eval = TRUE, fig.width = 6, warning = FALSE,
  message = FALSE, fig.asp = 0.618, out.width = "80%", dpi = 120,
  fig.align = "center", cache = FALSE
)

# Load required packages
suppressPackageStartupMessages(library(tidyverse, quietly = TRUE))
suppressPackageStartupMessages(library(jsonlite))
suppressPackageStartupMessages(library(lubridate))
suppressPackageStartupMessages(library(openmeteo))
```

## Lab report
## Exercises
#### Exercise 1
https://www.latlong.net/ 
-  Here are my top picks for places to visit in the upcoming winter season.
-  228-33, Taegi-ro, Bongpyeong-myeon, Pyeongchang-gun, Gangwon-do,
Republic of Korea
-  Lat Long is (37.581848, 128.327378)
and GPS Coordinates are (37° 34' 54.6528'' N 
128° 19' 38.5608'' E)

- Q) Find the coordinates using www.latlong.net
- A) <a href="https://www.latlong.net/c/?lat=37.593792&long=128.319656" target="_blank">(37.593792, 128.319656)</a>
     https://www.latlong.net/c/?lat=37.593792&long=128.319656

#### Exercise 2

```{r, warning=FALSE}
locations_page = fromJSON("https://api.openaq.org/v2/locations")

locations_df = as_tibble(locations_page$results)
```

#### Exercise 3
```{r, warning=FALSE}
locations_page = fromJSON("https://api.openaq.org/v2/locations?limit=100")
locations_df = as_tibble(locations_page$results)
```

#### Exericse 4
```{r, warning=FALSE}
locPage = fromJSON("https://api.openaq.org/v2/measurements?limit=10000")
locData = as_tibble(locPage$results)

# locData$parameter %>% unique() %>% sort()
# colnames(locData) 
statData = locData %>%
  filter(parameter %in% c("pm25", "so2", "o3")) %>%
  group_by(parameter) %>%
  summarize(
    meanVal = mean(value, na.rm = TRUE),
    minVal = min(value, na.rm = TRUE),
    maxVal = max(value, na.rm = TRUE),
    sdVal = sd(value, na.rm = TRUE),
    iqrVal = IQR(value, na.rm = TRUE)
  )

print(statData)
```



#### Exericse 5
```{r, warning=FALSE}
locDataL1 = locData %>%
  dplyr::mutate(dtDateTime = lubridate::ydm_hms(date$utc))

ggplot(locDataL1, aes(x = dtDateTime, y = value, group = 1)) +
  geom_line() +
  facet_wrap(~parameter, scales = 'free_y') +
  scale_x_datetime(date_labels = "%Y-%m-%d %H:%M:%S") +
  labs(x = "Date Time [UTC]", y = "Value", title = "Time Series Variation by Parameter")
```
