---
title: "Lab 8 - Basketball and Hot Hands"
author: "Sangwon Yum"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    highlight: tango
    toc: false
    df_print: kable
    fig_caption: no
    number_sections: no
    dev: pdf
    latex_engine: xelatex
  html_document:
    highlight: tango
    self_contained: true
    theme: paper
    toc: no
    df_print: kable
    fig_caption: no
    number_sections: no
    smart: yes
    dev: svg
  github_document:
    html_preview: false
    pandoc_args: --webtex
    toc: true
    toc_depth: 4
    dev: svg
    df_print: kable
---

```{r setup, include = FALSE}
# knitr::opts_chunk$set(
#   echo = TRUE, eval = TRUE, fig.width = 6, warning = FALSE,
#   message = FALSE,
#   fig.asp = 0.618, out.width = "80%", dpi = 120,
#   fig.align = "center", cache = FALSE
# )

# DO NOT ALTER CODE IN THIS CHUNK
# Set knitr options
knitr::opts_chunk$set(echo = TRUE)

# Load required packages
suppressPackageStartupMessages(library(tidyverse, quietly = TRUE))

# Load the dataset and source function
kobe_basket = read_rds("kobe_basket.rds")

source("calc_streak.R")
```

## Lab report
## Exercises
#### Exercise 1
- Q) Define streak length of 1
- A) How many hits?
- A) How many misses?
- Q) Define streak length of zero


<!-- - Q) Which summary statistics are sensitive to outliers? -->
<!-- - A) mean, sd, min, max -->
```{r, warning=FALSE}
kobe_streack = calc_streak(kobe_basket$shot)
print(kobe_streack)

# 연속 득점 길이가 1인 경우를 필터링
statData = kobe_streack %>% 
  dplyr::group_by(length) %>% 
  dplyr::summarise(
    cnt = n()
  )
print(statData)

# 히트와 미스의 수를 카운트
hitCnt = statData %>% dplyr::filter(length == 1)
print(hitCnt)

misCnt = length(statData) - hitCnt
print(misCnt)

zeroCnt = statData %>% dplyr::filter(length == 0)
print(zeroCnt)
``` 

#### Exercise 2
```{r, warning=FALSE}

```


#### Exercise 3
```{r, warning=FALSE}

```

#### Exericse 4
```{r, warning=FALSE}

```

## Additional questions
#### Question 1
```{r, warning=FALSE}

```

#### Question 2
```{r, warning=FALSE}

```

#### Question 3
```{r, warning=FALSE}

```

#### Question 4
```{r, warning=FALSE}

```