---
title: "R을 이용한 자유 주제에 대한 보고서: R을 이용한 서울시 아파트 실거래가 회귀분석 및 주택가격 결정 요인"
date: "Submission date: `r Sys.setlocale('LC_TIME','C'); format(Sys.Date(), format='%B %d, %Y')`"
output:
 rmdformats::readthedown:
  highlight: kate
  self_contained: true
  gallery: true
  lightbox: true
  number_section: true
  toc_depth: 6
subtitle: "<p><font size='4'><span style='line-height: 100%'> 
  이종호, 배광원, 정지영 </span></font></p>"
editor_options: 
  chunk_output_type: inline
---

```{r include=FALSE, warning=FALSE}
#================================================
# Set Env
#================================================
globalVar = list()
globalVar$inpPath = "."
globalVar$figPath = "."
globalVar$outPath = "."
globalVar$mapPath = "."

serviceName = "LSH0178"
```

```{r include=FALSE, warning=FALSE}
#================================================
# Main
#================================================
library(ggplot2)
library(tidyverse)
library(httr)
library(rvest)
library(jsonlite)
library(RCurl)
library(readr)
library(magrittr)
library(ggrepel)
library(colorRamps)
library(ggpubr)
library(lm.beta)
library(ggpmisc)
# unloadNamespace('raster')
library(gstat)
library(sf)

cbMatlab = colorRamps::matlab.like(11)

# 공공데이터포털 API키
# reqDataKey = globalVar$dataKey
reqDataKey = "Ftj0WhfmnXN86rrVCPTGvlQJ%oJs9l+ZQjJzPgtc37yVPWuXs8UOP3kD2lTyy9DFInQZj2VvYFH1+Uh7gNgTLLA=="

# 요청 URL
reqUrl = "http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade"
# 요청 키
reqKey = stringr::str_c("?serviceKey=", RCurl::curlEscape(stringr::str_conv(reqDataKey, encoding = "UTF-8")))

```

# 종속변수 선정
## 상권 자료(market) 정리, 영업지수 산출

```{r message=FALSE, warning=FALSE, paged.print=TRUE}
market <- readr::read_csv("market.csv", locale=locale(encoding="EUC-KR"))
paged_table(market)

code <- readr::read_csv("code.csv", locale=locale(encoding="EUC-KR")) %>%
  select(-코드_2) %>% rename("코드"="코드_1")

marche <- market %>% unite("연도_분기", 기준_년_코드, 기준_분기_코드) %>%
  filter(연도_분기 %in% "2019_4") %>%
  mutate(운영개월 = 서울_운영_영업_개월_평균 - 운영_영업_개월_평균,
         폐업개월 = -(서울_폐업_영업_개월_평균 - 폐업_영업_개월_평균),
         영업지수 = 운영개월 + 폐업개월) %>%
  select(-상권_변화_지표_명, -운영_영업_개월_평균, -폐업_영업_개월_평균,
         -서울_운영_영업_개월_평균, -서울_폐업_영업_개월_평균) %>%
  rename("행정동"="행정동_코드_명", "코드"="행정동_코드")

markt <- left_join(marche, code, by="코드") %>%
  select(-행정동.x) %>%
  unite("자치구_행정동", 구, 행정동.y) %>%
  relocate(연도_분기, 코드, 자치구_행정동, 상권_변화_지표, 운영개월, 폐업개월, 영업지수)
paged_table(markt)

ggplot(markt, aes(x=운영개월, y=폐업개월))+
  geom_point(mapping=aes(color=상권_변화_지표))+
  scale_color_manual(values=c("palevioletred2", "lightgoldenrod", "seagreen3", "slateblue"))+
  theme_minimal()+theme(legend.position=c(0.9, 0.5))

ggplot(data=markt, mapping=aes(x=reorder(자치구_행정동, 영업지수), y=영업지수, fill=상권_변화_지표))+
  scale_fill_manual(values=c("palevioletred2", "lightgoldenrod", "seagreen3", "slateblue"))+
  geom_bar(stat="identity")+
  theme(axis.text.x=element_blank())+
  theme(legend.position=c(0.9, 0.2))
```
<br>
<br>

# 독립변수 설정
## 서비스업 자료(business_type)의 분류
### 자료 정리

```{r message=FALSE, warning=FALSE, paged.print=TRUE}
type <- readr::read_csv("business_type.csv", locale=locale(encoding="EUC-KR"))
paged_table(type)

sorte <- type %>%
  filter(!(행정동 %in% c("행정동", "합계", "소계"))) %>%
  select(-사업체수_1, -종사자수_1, -종사자수_2) %>%
  unite("자치구_행정동", 구, 행정동) %>%
  rename("D.전기가스공급업_사업체수"="D. 전기 가스 증기 및 공기조절 공급업",
         "D.전기가스공급업_종사자수"="D. 전기 가스 증기 및 공기조절 공급업_1",
         "E.수도하수재생업_사업체수"="E. 수도 하수 및 폐기물 처리 원료 재생업",
         "E.수도하수재생업_종사자수"="E. 수도 하수 및 폐기물 처리 원료 재생업_1",
         "F.건설업_사업체수"="F. 건설업", "F.건설업_종사자수"="F. 건설업_1",
         "G.도소매업_사업체수"="G. 도매 및 소매업", "G.도소매업_종사자수"="G. 도매 및 소매업_1",
         "H.운수창고업_사업체수"="H. 운수 및 창고업", "H.운수창고업_종사자수"="H. 운수 및 창고업_1",
         "I.숙박요식업_사업체수"="I. 숙박 및 음식점업", "I.숙박요식업_종사자수"="I. 숙박 및 음식점업_1",
         "J.정보통신업_사업체수"="J. 정보통신업", "J.정보통신업_종사자수"="J. 정보통신업_1",
         "K.금융보험업_사업체수"="K. 금융 및 보험업", "K.금융보험업_종사자수"="K. 금융 및 보험업_1",
         "L.부동산업_사업체수"="L. 부동산업", "L.부동산업_종사자수"="L. 부동산업_1",
         "M.전문과학기술업_사업체수"="M. 전문 과학 및 기술 서비스업",
         "M.전문과학기술업_종사자수"="M. 전문 과학 및 기술 서비스업_1",
         "N.사업시설관리임대업_사업체수"="N. 사업시설 관리 사업 지원 및 임대 서비스업",
         "N.사업시설관리임대업_종사자수"="N. 사업시설 관리 사업 지원 및 임대 서비스업_1",
         "O.공공행정국방업_사업체수"="O. 공공행정 국방 및 사회보장 행정",
         "O.공공행정국방업_종사자수"="O. 공공행정 국방 및 사회보장 행정_1",
         "P.교육서비스업_사업체수"="P. 교육 서비스업", "P.교육서비스업_종사자수"="P. 교육 서비스업_1",
         "Q.보건사회복지서비스업_사업체수"="Q. 보건업 및 사회복지 서비스업",
         "Q.보건사회복지서비스업_종사자수"="Q. 보건업 및 사회복지 서비스업_1",
         "R.예술체육여가서비스업_사업체수"="R. 예술 스포츠 및 여가관련 서비스업",
         "R.예술체육여가서비스업_종사자수"="R. 예술 스포츠 및 여가관련 서비스업_1",
         "S.기타개인서비스업_사업체수"="S. 협회 및 단체 수리 및 기타 개인 서비스업",
         "S.기타개인서비스업_종사자수"="S. 협회 및 단체 수리 및 기타 개인 서비스업_1") %>%
  mutate(사업체수=str_replace(사업체수, ",", ""), 종사자수=str_replace(종사자수, ",", ""),
         D.전기가스공급업_사업체수=str_replace(D.전기가스공급업_사업체수, ",", ""),
         D.전기가스공급업_종사자수=str_replace(D.전기가스공급업_종사자수, ",", ""),
         E.수도하수재생업_사업체수=str_replace(E.수도하수재생업_사업체수, ",", ""),
         E.수도하수재생업_종사자수=str_replace(E.수도하수재생업_사업체수, ",", ""),
         F.건설업_사업체수=str_replace(F.건설업_사업체수, ",", ""),
         F.건설업_종사자수=str_replace(F.건설업_종사자수, ",", ""),
         G.도소매업_사업체수=str_replace(G.도소매업_사업체수, ",", ""),
         G.도소매업_종사자수=str_replace(G.도소매업_종사자수, ",", ""),
         H.운수창고업_사업체수=str_replace(H.운수창고업_사업체수, ",", ""),
         H.운수창고업_종사자수=str_replace(H.운수창고업_종사자수, ",", ""),
         I.숙박요식업_사업체수=str_replace(I.숙박요식업_사업체수, ",", ""),
         I.숙박요식업_종사자수=str_replace(I.숙박요식업_종사자수, ",", ""),
         J.정보통신업_사업체수=str_replace(J.정보통신업_사업체수, ",", ""),
         J.정보통신업_종사자수=str_replace(J.정보통신업_종사자수, ",", ""),
         K.금융보험업_사업체수=str_replace(K.금융보험업_사업체수, ",", ""),
         K.금융보험업_종사자수=str_replace(K.금융보험업_종사자수, ",", ""),
         L.부동산업_사업체수=str_replace(L.부동산업_사업체수, ",", ""),
         L.부동산업_종사자수=str_replace(L.부동산업_종사자수, ",", ""),
         M.전문과학기술업_사업체수=str_replace(M.전문과학기술업_사업체수, ",", ""),
         M.전문과학기술업_종사자수=str_replace(M.전문과학기술업_종사자수, ",", ""),
         N.사업시설관리임대업_사업체수=str_replace(N.사업시설관리임대업_사업체수, ",", ""),
         N.사업시설관리임대업_종사자수=str_replace(N.사업시설관리임대업_종사자수, ",", ""),
         O.공공행정국방업_사업체수=str_replace(O.공공행정국방업_사업체수, ",", ""),
         O.공공행정국방업_종사자수=str_replace(O.공공행정국방업_종사자수, ",", ""),
         P.교육서비스업_사업체수=str_replace(P.교육서비스업_사업체수, ",", ""),
         P.교육서비스업_종사자수=str_replace(P.교육서비스업_종사자수, ",", ""),
         Q.보건사회복지서비스업_사업체수=str_replace(Q.보건사회복지서비스업_사업체수, ",", ""),
         Q.보건사회복지서비스업_종사자수=str_replace(Q.보건사회복지서비스업_종사자수, ",", ""),
         R.예술체육여가서비스업_사업체수=str_replace(R.예술체육여가서비스업_사업체수, ",", ""),
         R.예술체육여가서비스업_종사자수=str_replace(R.예술체육여가서비스업_종사자수, ",", ""),
         S.기타개인서비스업_사업체수=str_replace(S.기타개인서비스업_사업체수, ",", ""),
         S.기타개인서비스업_종사자수=str_replace(S.기타개인서비스업_종사자수, ",", ""))

sorte$사업체수 <- as.numeric(sorte$사업체수)
sorte$종사자수 <- as.numeric(sorte$종사자수)
sorte$D.전기가스공급업_사업체수 <- as.numeric(sorte$D.전기가스공급업_사업체수)
sorte$D.전기가스공급업_종사자수 <- as.numeric(sorte$D.전기가스공급업_종사자수)
sorte$E.수도하수재생업_사업체수 <- as.numeric(sorte$E.수도하수재생업_사업체수)
sorte$E.수도하수재생업_종사자수 <- as.numeric(sorte$E.수도하수재생업_종사자수)
sorte$F.건설업_사업체수 <- as.numeric(sorte$F.건설업_사업체수)
sorte$F.건설업_종사자수 <- as.numeric(sorte$F.건설업_종사자수)
sorte$G.도소매업_사업체수 <- as.numeric(sorte$G.도소매업_사업체수)
sorte$G.도소매업_종사자수 <- as.numeric(sorte$G.도소매업_종사자수)
sorte$H.운수창고업_사업체수 <- as.numeric(sorte$H.운수창고업_사업체수)
sorte$H.운수창고업_종사자수 <- as.numeric(sorte$H.운수창고업_종사자수)
sorte$I.숙박요식업_사업체수 <- as.numeric(sorte$I.숙박요식업_사업체수)
sorte$I.숙박요식업_종사자수 <- as.numeric(sorte$I.숙박요식업_종사자수)
sorte$J.정보통신업_사업체수 <- as.numeric(sorte$J.정보통신업_사업체수)
sorte$J.정보통신업_종사자수 <- as.numeric(sorte$J.정보통신업_종사자수)
sorte$K.금융보험업_사업체수 <- as.numeric(sorte$K.금융보험업_사업체수)
sorte$K.금융보험업_종사자수 <- as.numeric(sorte$K.금융보험업_종사자수)
sorte$L.부동산업_사업체수 <- as.numeric(sorte$L.부동산업_사업체수)
sorte$L.부동산업_종사자수 <- as.numeric(sorte$L.부동산업_종사자수)
sorte$M.전문과학기술업_사업체수 <- as.numeric(sorte$M.전문과학기술업_사업체수)
sorte$M.전문과학기술업_종사자수 <- as.numeric(sorte$M.전문과학기술업_종사자수)
sorte$N.사업시설관리임대업_사업체수 <- as.numeric(sorte$N.사업시설관리임대업_사업체수)
sorte$N.사업시설관리임대업_종사자수 <- as.numeric(sorte$N.사업시설관리임대업_종사자수)
sorte$O.공공행정국방업_사업체수 <- as.numeric(sorte$O.공공행정국방업_사업체수)
sorte$O.공공행정국방업_종사자수 <- as.numeric(sorte$O.공공행정국방업_종사자수)
sorte$P.교육서비스업_사업체수 <- as.numeric(sorte$P.교육서비스업_사업체수)
sorte$P.교육서비스업_종사자수 <- as.numeric(sorte$P.교육서비스업_종사자수)
sorte$Q.보건사회복지서비스업_사업체수 <- as.numeric(sorte$Q.보건사회복지서비스업_사업체수)
sorte$Q.보건사회복지서비스업_종사자수 <- as.numeric(sorte$Q.보건사회복지서비스업_종사자수)
sorte$R.예술체육여가서비스업_사업체수 <- as.numeric(sorte$R.예술체육여가서비스업_사업체수)
sorte$R.예술체육여가서비스업_종사자수 <- as.numeric(sorte$R.예술체육여가서비스업_종사자수)
sorte$S.기타개인서비스업_사업체수 <- as.numeric(sorte$S.기타개인서비스업_사업체수)
sorte$S.기타개인서비스업_종사자수 <- as.numeric(sorte$S.기타개인서비스업_종사자수)
```

```{r message=FALSE, warning=FALSE, paged.print=TRUE}
par(mfrow=c(1,3), cex=.5)

plot(log(sorte$종사자수), log(sorte$G.도소매업_종사자수+1), col="white", ylim=c(0,10.5))
abline(lm(log(sorte$G.도소매업_종사자수+1)~log(sorte$종사자수)), col="orange")
abline(lm(log(sorte$I.숙박요식업_종사자수+1)~log(sorte$종사자수)), col="palegoldenrod")
abline(lm(log(sorte$L.부동산업_종사자수+1)~log(sorte$종사자수)), col="peachpuff2")
abline(lm(log(sorte$R.예술체육여가서비스업_종사자수+1)~log(sorte$종사자수)), col="yellow2")
abline(lm(log(sorte$S.기타개인서비스업_종사자수+1)~log(sorte$종사자수)), col="yellow4")
legend("topleft", legend=c("G.도소매업", "I.숙박요식업", "L.부동산업",
                               "R.예술체육여가서비스업", "S.기타개인서비스업"), 
       col=c("orange", "palegoldenrod", "peachpuff2", "yellow2", "yellow4"), lty=1)

plot(log(sorte$종사자수), log(sorte$M.전문과학기술업_종사자수+1), col="white", ylim=c(0,10.5))
abline(lm(log(sorte$F.건설업_종사자수+1)~log(sorte$종사자수)), col="yellowgreen")
abline(lm(log(sorte$J.정보통신업_종사자수+1)~log(sorte$종사자수)), col="seagreen")
abline(lm(log(sorte$K.금융보험업_종사자수+1)~log(sorte$종사자수)), col="springgreen4")
abline(lm(log(sorte$M.전문과학기술업_종사자수+1)~log(sorte$종사자수)), col="turquoise")
abline(lm(log(sorte$N.사업시설관리임대업_종사자수+1)~log(sorte$종사자수)), col="skyblue2")
legend("topleft", legend=c("F.건설업", "J.정보통신업", "K.금융보험업",
                               "M.전문과학기술업", "N.사업시설관리임대업"), 
       col=c("yellowgreen", "seagreen", "springgreen4", "turquoise", "skyblue2"), lty=1)

plot(log(sorte$종사자수), log(sorte$P.교육서비스업_종사자수+1), col="white", ylim=c(0,10.5))
abline(lm(log(sorte$D.전기가스공급업_종사자수+1)~log(sorte$종사자수)), col="lightpink")
abline(lm(log(sorte$E.수도하수재생업_종사자수+1)~log(sorte$종사자수)), col="lightcoral")
abline(lm(log(sorte$H.운수창고업_종사자수+1)~log(sorte$종사자수)), col="salmon2")
abline(lm(log(sorte$O.공공행정국방업_종사자수+1)~log(sorte$종사자수)), col="royalblue2")
abline(lm(log(sorte$P.교육서비스업_종사자수+1)~log(sorte$종사자수)), col="slateblue")
abline(lm(log(sorte$Q.보건사회복지서비스업_종사자수+1)~log(sorte$종사자수)), col="mediumorchid4")
legend("topleft", legend=c("D.전기가스공급업", "E.수도하수재생업", "H.운수창고업",
                               "O.공공행정국방업", "P.교육서비스업", "Q.보건사회복지서비스업"), 
       col=c("lightpink", "lightcoral", "salmon2", "royalblue2", "slateblue", "mediumorchid4"), lty=1)
```
<br>
<br>

### 유형별 종사자수 합산

```{r message=FALSE, warning=FALSE, paged.print=TRUE}
sorte[is.na(sorte)] <- 0

gattung <- sorte %>%
  mutate(소비자서비스업 = G.도소매업_종사자수 + I.숙박요식업_종사자수 +
           L.부동산업_종사자수 + R.예술체육여가서비스업_종사자수 + S.기타개인서비스업_종사자수,
         생산자서비스업 = F.건설업_종사자수 + J.정보통신업_종사자수 +
           K.금융보험업_종사자수 + M.전문과학기술업_종사자수 + N.사업시설관리임대업_종사자수,
         전체서비스업 = 소비자서비스업 + 생산자서비스업,
         소비자서비스업비율 = 소비자서비스업 / 전체서비스업,
         생산자서비스업비율 = 생산자서비스업 / 전체서비스업) %>%
  select(자치구_행정동, 종사자수, 소비자서비스업, 생산자서비스업, 소비자서비스업비율, 생산자서비스업비율)

alpha <- left_join(markt, gattung, by="자치구_행정동") %>%
  select(-종사자수)
paged_table(alpha)
```

```{r message=FALSE, warning=FALSE, paged.print=TRUE}
par(mfrow=c(1,2), cex=.6)

plot(log(alpha$소비자서비스업), alpha$영업지수)
abline(lm(alpha$영업지수~log(alpha$소비자서비스업)), col="slateblue")

plot(log(alpha$생산자서비스업+1), alpha$영업지수)
abline(lm(alpha$영업지수~log(alpha$생산자서비스업+1)), col="deeppink")

summary(lm(영업지수~log(소비자서비스업), alpha))
summary(lm(영업지수~log(생산자서비스업+1), alpha))
```

```{r message=FALSE, warning=FALSE, paged.print=TRUE}
par(mfrow=c(1,2), cex=.6)

plot(alpha$소비자서비스업비율, alpha$영업지수)
abline(lm(alpha$영업지수~alpha$소비자서비스업비율), col="slateblue")

plot(alpha$생산자서비스업비율, alpha$영업지수)
abline(lm(alpha$영업지수~alpha$생산자서비스업비율), col="deeppink")

summary(lm(영업지수~소비자서비스업비율, alpha))
summary(lm(영업지수~생산자서비스업비율, alpha))
```
<br>
<br>

## 사업체수 자료(business_number) 정리
```{r message=FALSE, warning=FALSE, paged.print=TRUE}
number <- readr::read_csv("business_number.csv", locale=locale(encoding="EUC-KR"))
paged_table(number)

nombre <- number %>%
  select(구, 행정동, 사업체수, 평균종사자, 종사자밀도비) %>%
  unite("자치구_행정동", 구, 행정동)

beta <- left_join(alpha, nombre, by="자치구_행정동")
paged_table(beta)
```

```{r message=FALSE, warning=FALSE, paged.print=TRUE}
par(mfrow=c(1,3), cex=.5)

plot(log(beta$사업체수), beta$영업지수)
abline(lm(beta$영업지수~log(beta$사업체수)), col="slateblue")

plot(log(beta$평균종사자), beta$영업지수)
abline(lm(beta$영업지수~log(beta$평균종사자)), col="deeppink")

plot(log(beta$종사자밀도비), beta$영업지수)
abline(lm(beta$영업지수~log(beta$종사자밀도비)), col="lightseagreen")

summary(lm(영업지수~log(사업체수), beta))
summary(lm(영업지수~log(평균종사자), beta))
summary(lm(영업지수~log(종사자밀도비), beta))
```

<br>
<br>

## 사업체 영업기간 자료(business_age) 정리

```{r message=FALSE, warning=FALSE, paged.print=TRUE}
age <- readr::read_csv("business_age.csv", locale=locale(encoding="EUC-KR"))
paged_table(age)

annee <- age %>%
  separate(사업체_평균연령, into=c("연", "개월"), sep="년", convert=T) %>%
  separate(개월, into=c("숫자", "문자"), sep="개월", convert=T) %>%
  select(-문자) %>% mutate(월 = 숫자/12) %>%
  select(-숫자) %>% mutate(사업체_영업기간 = 연 + 월) %>%
  select(-연, -월) %>% filter(!(행정동 %in% c("합계", "소계"))) %>%
  unite("자치구_행정동", 구, 행정동)


gamma <- left_join(beta, annee, by="자치구_행정동") %>%
  select(-사업체수.y, -평균종사자.y, -종사자수) %>%
  rename("사업체수"="사업체수.x", "평균종사자"="평균종사자.x") %>%
  relocate(연도_분기, 코드, 자치구_행정동, 상권_변화_지표, 운영개월, 폐업개월, 영업지수,
           소비자서비스업, 생산자서비스업, 소비자서비스업비율, 생산자서비스업비율,
           사업체수, 평균종사자, 종사자밀도비, 사업체_영업기간)
paged_table(gamma)
```

```{r message=FALSE, warning=FALSE, paged.print=TRUE}
plot(gamma$사업체_영업기간, gamma$영업지수)
abline(lm(gamma$영업지수~gamma$사업체_영업기간), col="slateblue")

summary(lm(gamma$영업지수~gamma$사업체_영업기간))
```
<br>
<br>

## 사업체 창업률 자료(business_founding) 정리

```{r message=FALSE, warning=FALSE, paged.print=TRUE}
founding <- readr::read_csv("business_founding.csv", locale=locale(encoding="EUC-KR"))
paged_table(founding)

fondation <- founding %>%
  filter(!(행정동 %in% c("합계", "소계"))) %>%
  unite("자치구_행정동", 구, 행정동)

delta <- left_join(gamma, fondation, by="자치구_행정동") %>%
  select(-사업체수.y, -평균종사자.y, -종사자수) %>%
  rename("사업체수"="사업체수.x", "평균종사자"="평균종사자.x")
paged_table(delta)
```

```{r message=FALSE, warning=FALSE, paged.print=TRUE}
plot(delta$사업체_창업률, delta$영업지수)
abline(lm(delta$영업지수~delta$사업체_창업률), col="slateblue")

ggplot(data=delta, aes(x=사업체_창업률,y= 영업지수,color=상권_변화_지표),  fill=상권_변화_지표) + geom_point()  +
  scale_fill_manual(values=c("palevioletred2", "lightgoldenrod", "seagreen3", "slateblue"))+
  theme(axis.text.x=element_blank())+
  theme(legend.position=c(0.9, 0.2))+geom_smooth(method=lm)

```
<br>
<br>

## 자영업 종사자수 자료(business_private) 정리

```{r message=FALSE, warning=FALSE, paged.print=TRUE}
private <- readr::read_csv("business_private.csv", locale=locale(encoding="EUC-KR"))
paged_table(private)

prive <- private %>%
  filter(!(행정동 %in% c("합계", "소계"))) %>%
  select(구, 행정동, 자영업주_및_무급가족_소계, 자영업주_및_무급가족_여성종사자,상용근로자_소계,임시_및_일용근로자_소계,기타종사자_소계) %>%
  unite("자치구_행정동", 구, 행정동)%>% mutate(자영업비율 = 자영업주_및_무급가족_소계/(자영업주_및_무급가족_소계+임시_및_일용근로자_소계+기타종사자_소계+상용근로자_소계)*100
                                          , 자영업_종사자수 = 자영업주_및_무급가족_소계
                                          ) 

epsilon <- left_join(delta, prive, by="자치구_행정동")
paged_table(epsilon)
```

```{r message=FALSE, warning=FALSE, paged.print=TRUE}
par(mfrow=c(1,2), cex=0.6)
plot(epsilon$자영업_종사자수, epsilon$영업지수)
abline(lm(epsilon$영업지수~epsilon$자영업_종사자수), col="slateblue")

plot(log(epsilon$자영업_종사자수), epsilon$영업지수)
abline(lm(epsilon$영업지수~log(epsilon$자영업_종사자수)), col="deeppink")

summary(lm(epsilon$영업지수~epsilon$자영업_종사자수))
summary(lm(epsilon$영업지수~(log(epsilon$자영업_종사자수))))


##########자영업 비율 추가#####################

plot(epsilon$자영업비율, epsilon$영업지수)
abline(lm(epsilon$영업지수 ~ epsilon$자영업비율), col="slateblue")


plot(log(epsilon$자영업비율), epsilon$영업지수)
abline(lm(epsilon$영업지수~log(epsilon$자영업비율)), col="slateblue")


summary(lm(epsilon$영업지수~epsilon$자영업비율))
summary(lm(epsilon$영업지수~(log(epsilon$자영업비율))))



ggplot(data=epsilon, aes(x=자영업비율,y= 영업지수,color=상권_변화_지표),  fill=상권_변화_지표) + geom_point()  +
  scale_fill_manual(values=c("palevioletred2", "lightgoldenrod", "seagreen3", "slateblue"))+
  theme(axis.text.x=element_blank())+
  theme(legend.position=c(0.9, 0.2))+geom_smooth(method=lm)

```

```{r message=FALSE, warning=FALSE, paged.print=TRUE}
summary(lm(영업지수~사업체_영업기간*사업체_창업률*자영업_종사자수, epsilon))
```
<br>
<br>



     
