---
title: "psych 데이터 기반으로 요인 분석 (탐색적 요인 분석 EFA, 확인적 요인 분석 CFA"
author: "성명"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: yes
    dev: cairo_pdf
    fig_caption: yes
    number_sections: yes
    toc: no
    df_print: kable
mainfont: "Malgun Gothic"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE, eval = TRUE, fig.width = 6, warning = FALSE,
  message = FALSE, fig.asp = 0.618, out.width = "80%", dpi = 120,
  fig.align = "center", cache = FALSE
)
```

# 자료 읽기
```{r, warning=FALSE}
# data read
data(bfi, package = "psych")

# select columns
dataL1 = bfi[, c("A1", "A2", "A3", "A4", "A5",
                 "C1", "C2", "C3", "C4", "C5",
                 "E1", "E2", "E3", "E4", "E5",
                 "N1", "N2", "N3", "N4", "N5",
                 "O1", "O2", "O3", "O4", "O5")]

# library read
suppressPackageStartupMessages(library(psych))
suppressPackageStartupMessages(library(lavaan))
```

# Exploratory Factor Analysis, EFA
```{r, warning=FALSE}
# run EFA Model
efaModel = psych::fa(dataL1, nfactors=5)

# result
print(efaModel)


# [EFA 분석 결과]
# # 요인 적재
# MR1 요인은 전체 분산의 18%를 설명하고 MR2 요인은 전체 분산의 9%를 설명함
# 따라서 MR1~5 요인까지 고려할 경우 전체 분산의 41% 설명력을 지님
# 
# # 적합도 지표
# RMSEA (Root Mean Square Error of Approximation)는 0.056로서 90% 신뢰구간은 0.054에서 0.058로 분포하고 0.05 이하에서 좋은 적합 성능을 보임
# 나아가 RMSR (The root mean square of the residuals), TLI (Tucker Lewis Index), BIC(Bayesian Information Criterion)와 같은 검증 지표에서도 유사한 성능을 보임
# 
# # 요인 점수 적합성
# 해당 요인과 MR1~MR5의 최소 상관계수는 0.26 ~ 0.79로 분포하고 특히 MR1 요인과 가장 높은 상관성 (0.95)을 보임
``` 
  
# Confirmatory Factor Analysis, CFA
```{r, warning=FALSE, echo=FALSE}
#  set CFA Model
model = '
  A =~ A1 + A2 + A3 + A4 + A5
  C =~ C1 + C2 + C3 + C4 + C5
  E =~ E1 + E2 + E3 + E4 + E5
  N =~ N1 + N2 + N3 + N4 + N5
  O =~ O1 + O2 + O3 + O4 + O5
'

# run CFA Model
cfaModel = lavaan::cfa(model, data=dataL1)

# result
summary(cfaModel, fit.measures=TRUE)

# [CFA 분석 결과]
# # 모델 적합도
# 카이제곱 통계량 (Chi-square)은 4165.467이고 유의수준 (p-value) 0.000으로서 통계적으로 유의함
# RMSEA (Root Mean Square Error of Approximation)는 0.078로서 0.05 이하에서 보통 이상의 적합 성능을 보임
# 나아가 CFI (Comparative Fit Index), TLI (Tucker-Lewis Index)와 같은 검증 지표에서도 유사한 성능을 보임
# 
# # 요인 부하 
# 모든 변수들의 요인 부하의 경우 유의수준 0.000으로서 통계적으로 유의미함
# 
# # 요인 간의 공변성
# 잠재 변수들 간의 관계도 역시 통계적으로 유의미함
# 
# # 분산
# 각 변수와 잠재 변수의 분산 또한 통계적으로 유의미함
```